/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type RoomType = 'standard' | 'suite' | 'cabin';
export type RoomStatus = 'available' | 'occupied' | 'cleaning' | 'maintenance';
export type BookingPlatform = 'web' | 'booking' | 'expedia' | 'reception';
export type BookingStatus = 'confirmed' | 'active' | 'checked-out' | 'cancelled';
export type EmployeeRole = 'reception' | 'cleaning' | 'maintenance' | 'chef' | 'spa';
export type EmployeeStatus = 'present' | 'absent' | 'vacation' | 'sick';
export type SubcontractorService = 'water' | 'electricity' | 'elevator' | 'spa' | 'heating';
export type SubcontractorStatus = 'ok' | 'pending-review' | 'alert';
export type SenderRole = 'consumer' | 'receptionist' | 'admin';

export interface Room {
  id: number;
  number: string;
  name: string;
  type: RoomType;
  capacity: number;
  price: number;
  status: RoomStatus;
  features: string[];
  image: string;
}

export interface Booking {
  id: string;
  guestName: string;
  guestEmail: string;
  roomId: number;
  checkIn: string;
  checkOut: string;
  totalPrice: number;
  platform: BookingPlatform;
  status: BookingStatus;
  createdAt: string;
  invoiceNumber: string;
}

export interface Employee {
  id: string;
  name: string;
  role: EmployeeRole;
  dni: string;
  contractType: string;
  startDate: string;
  vacationsTaken: number;
  vacationsTotal: number;
  status: EmployeeStatus;
  sickLeaves: number;
  tenure: string;
  hourlySchedule: string;
  todayClockIn?: string;
  todayClockOut?: string;
}

export interface Subcontractor {
  id: string;
  company: string;
  service: SubcontractorService;
  contact: string;
  lastReview: string;
  nextReview: string;
  activeTickets: {
    id: string;
    title: string;
    status: 'open' | 'resolved';
    date: string;
  }[];
  status: SubcontractorStatus;
}

export interface ChatMessage {
  id: string;
  senderRole: SenderRole;
  senderName: string;
  message: string;
  timestamp: string;
}

export interface EnergyStats {
  timestamp: string;
  gridPowerkW: number;      // Power drawn from grid
  solarPowerkW: number;     // Power generated by solar array
  biomassTempC: number;     // Temp of biomass heating boiler
  waterFlowLpm: number;     // Water consumption in Liters Per Minute
}

export interface HotelData {
  rooms: Room[];
  bookings: Booking[];
  employees: Employee[];
  subcontractors: Subcontractor[];
  chats: ChatMessage[];
}
